# Setup
title:               ByeTools
tagline:             'A modular program for tools'
description:         'A modular program that <em><strong>ANYONE</strong></em> with <a href="https://python.org/>Python</a> knowledge can write stuff for. <br /> <small>still working on the modular bit</small>'
url:                 http://byetools.byemc.xyz
baseurl:             '/lanyon'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              ByeMC
  url:               https://twitter.com/_byemc
  email:             byemc@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
